<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\Db\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Report
 *
 * Structure class for relation public.report.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Report extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.report')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('reported_post', 'int4')
            ->addField('reported_user', 'int4')
            ->addField('reported_by', 'int4')
            ->addField('body', 'text')
            ->addField('body_xml', 'text')
            ->addField('when_created', 'timestamptz')
            ;
    }
}
