<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace App\Model\Db\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * User
 *
 * Structure class for relation public.user.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class User extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.user')
            ->setPrimaryKey(['id'])
            ->addField('id', 'int4')
            ->addField('external_id', 'text')
            ->addField('display_name', 'text')
            ->addField('rank', 'int4')
            ->addField('email', 'text')
            ->addField('signature', 'text')
            ->addField('signature_xml', 'text')
            ->addField('locale', 'varchar')
            ->addField('timezone', 'varchar')
            ->addField('topics', 'int4')
            ->addField('posts', 'int4')
            ->addField('registration_ip', 'inet')
            ->addField('last_ip', 'inet')
            ->addField('when_created', 'timestamptz')
            ->addField('last_visit', 'timestamptz')
            ->addField('last_post', 'timestamptz')
            ;
    }
}
